### PR TITLE
Note about vbguest plugin

### PR DESCRIPTION
**Pull request by dereuromark**

### CODE REVIEW

**Comment by marius-rizac** [comment]
:+1:

**Comment by anusch-athari** [comment]
I don't think this is the right solution to the problem.

**Comment by dereuromark** [comment]
We let @marek-obuchowicz or Marcel then decide on the approach here. Either document it or include it in the automatic setup process IMO.

**Comment by marek-obuchowicz** [comment]
Having *always* a proper version of Virtualbox guest addons would require rebuilding base box on each virtualbox release. This could be delivered as an automated solution, which builds a new base box on each Virtualbox release. We don't have it at the moment, therefore I think that installing latest vbguest additions with plugin makes sense, as it will allow the last (the default) version of Virtualbox to run on developers workstation. Forcing a specific version of Virtualbox is also a solution, but it's least preferred solution for me. First of all - we will have to do manual work "from time to time" to keep it *somehow* up-to-date with Virtualbox (we shouldn't require, for example, one year old version). Second - if some developer already has a Virtualbox which is newer than our supported version, the we will force the developer to downgrade, which can break any other VMs he already has.
@durandom your feedback is welcome

**Comment by anusch-athari** [comment]
Since we don't have the automated box building solution the plugin might be our best bet.
:+1: from me

**Comment by durandom** [comment]
ok for me, for the same reason that @anusch-athari pointed out.

**Pull request merged**
