### PR TITLE
Improvements/git

### PR DESCRIPTION
**Pull request by m7moud**
Depends and based on https://github.com/spryker/devvm/pull/32

### CODE REVIEW

**Comment by marek-obuchowicz** [comment]
Rejected. Some windows customers have requested using different setup, where code is *inside* the devvm and not on host OS. In that case there's no requirement for git executable on host os.

**Comment by m7moud** [comment]
But it's a requirement already with the current master (https://github.com/spryker/devvm/blob/master/Vagrantfile-quick#L122), this is just DRYing the checks that are everywhere.

**Comment by marek-obuchowicz** [comment]
:-1: current master will *not* clone directory or use git if `SPRYKER_DIRECTORY` is present and spryker is already there, so it changes current logic

:-1: please keep `unless IS_WINDOWS` as `File.delete` was reported to fail on windows

**Comment by m7moud** [comment]
@marek-obuchowicz If the file exist in another OS, it should be removed (or not, it's a log file anyway)

I have it on MacOS setup, so I can also say that this file is not exclusively created for Windows.

**Comment by marek-obuchowicz** [comment]
sure, file is created on all systems, on windows we have problems with `File.delete`, so `... unless IS_WINDOWS` will delete it on linux/osx

**Pull request closed without merging**
