### PR TITLE
Windows support for synced folders

### PR DESCRIPTION
**Pull request by durandom**
This makes our devvm run on windows. It's the synced_folder setting that makes it work.

### CODE REVIEW

**Comment by anusch-athari** [comment]
Does this default to nfs on linux/mac?

**Comment by durandom** [comment]
I'm not sure. I think it defaults to vboxfs if you are using Virtualbox

**Comment by anusch-athari** [comment]
That's no good and would be a BC breaking change. :( I guess we would need a bit more logic here.

**Comment by marek-obuchowicz** [comment]
This has been addressed in this commit, which changes shared folder only for windows: https://github.com/spryker/devvm/commit/5cbce3c09dc7650760cff9d07251090df665ea4b

**Pull request closed without merging**
