### PR TITLE
Port forwarding should be working on windows or ignored by vagrant

### PR DESCRIPTION
**Pull request by m7moud**

### CODE REVIEW

**Comment by marek-obuchowicz** [comment]
Has this been tested?

**Comment by m7moud** [comment]
I have a windows machine now and I'm testing it, will let you know.

**Comment by m7moud** [comment]
Tested on Windows 10, I will install Windows 7 and re-test it.

**Comment by m7moud** [comment]
I think It works fine since version 1.6, the current stable vagrant version 1.9.

**Comment by marek-obuchowicz** [comment]
This functionality has been already pushed to development branch 👍

**Pull request closed without merging**
