### PR TITLE
renamed devvm

### PR DESCRIPTION
**Pull request by marius-rizac**

### CODE REVIEW

**Comment by dereuromark** [comment]
To not conflict with "old" one, right? Sounds good to me.

**Comment by marius-rizac** [comment]
Required by Gregor for hackaton

**Comment by anusch-athari** [comment]
This name should be dynamic. With this we will have the same problem as before, project VMs will just keep the name and conflict with the demoshop VM. According to Marcel he created a ticket for this after I reported it.

**Comment by marek-obuchowicz** [comment]
@anusch-athari this document describes initial steps after cloning reference repositories, please include the information about the need for change of dev vm name in Vagrantfile:
https://github.com/spryker/saltstack/

Using dynamic (folder-based) name might lead to issues with existing VM's, i think that clearly stating that it needs to be changed for all new projects is good (as some values, like `VM_IP` have to be changed anyway to use multiple Vagrant VMs)

**Comment by anusch-athari** [comment]
@marek-obuchowicz From my (limited) experience, nobody followed your steps and all projects use the default settings.

**Comment by marius-rizac** [comment]
As @marek-obuchowicz said, customers should change the default configurations for the project. But I don't think that if they won't do it they will have any problem with this. I don't expect that clients to change configurations, but we, as core developers should change configuration according to each project that we take part.

**Pull request merged**
